# Generated by Django 5.2.8 on 2025-12-31 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveSmallIntegerField(choices=[(1, 'اطلاعات اولیه'), (2, 'تکمیل اطلاعات'), (3, 'انتخاب کلاس'), (4, 'بارگذاری مدارک')], default=1)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('completed', 'تکمیل شده'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='registration_docs/')),
                ('doc_type', models.CharField(choices=[('id_card', 'شناسنامه'), ('insurance', 'بیمه ورزشی'), ('photo', 'عکس پرسنلی'), ('other', 'سایر')], max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registration.registration')),
            ],
            options={
                'verbose_name': 'مدرک ثبت نام',
                'verbose_name_plural': 'مدارک ثبت نام',
            },
        ),
    ]
