# Generated by Django 5.2.8 on 2026-01-05 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_registration_options_registration_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='current_step',
            field=models.PositiveSmallIntegerField(choices=[(1, 'اطلاعات اولیه'), (2, 'تکمیل اطلاعات'), (3, 'بارگذاری مدارک'), (4, 'اضافه به کلاس')], default=1, verbose_name='مرحله ثبت نام'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('completed', 'تکمیل شده'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='draft', max_length=20, verbose_name='وضعیت ثبت نام'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL, verbose_name='ورزشکار'),
        ),
        migrations.AlterField(
            model_name='registrationdocument',
            name='doc_type',
            field=models.CharField(choices=[('id_card', 'شناسنامه'), ('register_form', 'فرم ثبت نام'), ('insurance_card', 'بیمه ورزشی'), ('other', 'سایر')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='registrationdocument',
            unique_together={('registration', 'doc_type')},
        ),
    ]
