# Generated by Django 5.2.8 on 2025-12-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('announcements', 'Announcements'), ('reminders', 'Reminders'), ('salary', 'Salary')], max_length=20, null=True),
        ),
    ]
