# Generated by Django 5.2.8 on 2025-12-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('announcements', 'Announcements'), ('reminders', 'Reminders'), ('tuition', 'Tuition')], max_length=20, null=True),
        ),
    ]
