# Generated by Django 5.2.8 on 2025-12-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلان ها'},
        ),
    ]
