# Generated by Django 5.2.8 on 2026-01-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('announcements', 'Announcements'), ('reminders', 'Reminders'), ('tuition', 'Tuition'), ('courses', 'Courses'), ('registration', 'Registration')], max_length=20, null=True),
        ),
    ]
