# Generated by Django 5.2.8 on 2025-11-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['finished', 'time', 'created_at'], 'verbose_name': 'تقویم', 'verbose_name_plural': 'تقویم ها'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='finished',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
