# Generated by Django 5.2.8 on 2025-11-19 10:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='coach',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='09330932370', max_length=15, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر نیست.', regex='^(\\+98|0)?9\\d{9}$')], verbose_name='شماره موبایل'),
            preserve_default=False,
        ),
    ]
