# Generated by Django 5.2.8 on 2025-11-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_managers_alter_coach_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('coach', 'Coach'), ('athlete', 'Athlete')], default='athlete', max_length=20, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
