# Generated by Django 5.2.8 on 2025-11-25 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='previous_login',
            field=models.DateTimeField(auto_now=True, verbose_name='ورود قبلی'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس آی پی'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='آخرین لاگین'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
