# Generated by Django 5.2.8 on 2025-12-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_customuser_previous_login_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'verbose_name': 'تاریخچه ورود', 'verbose_name_plural': 'تاریخچه ورود ها'},
        ),
    ]
