# Generated by Django 5.2.8 on 2026-02-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_loginhistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='previous_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ورود قبلی'),
        ),
    ]
