# Generated by Django 5.2.8 on 2026-04-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_role_remove_customuser_role_customuser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='insurance',
            field=models.BooleanField(default=False, verbose_name='بیمه'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای بیمه'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(max_length=100, verbose_name='نام پدر'),
        ),
    ]
