# Generated by Django 5.2.8 on 2025-12-27 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'حضور و غیاب', 'verbose_name_plural': 'حضور ها و غیاب ها'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'کلاس', 'verbose_name_plural': 'کلاس ها'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'ثبت نام', 'verbose_name_plural': 'ثبت نام ها'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'جلسه', 'verbose_name_plural': 'جلسات'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'جدول زمانی', 'verbose_name_plural': 'جدول های زمانی'},
        ),
        migrations.AddField(
            model_name='course',
            name='class_status',
            field=models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='age_ranges',
            field=models.ManyToManyField(related_name='courses', to='training.agerange', verbose_name='رده\u200cهای سنی'),
        ),
        migrations.CreateModel(
            name='EnrollmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='enrollment_docs/')),
                ('doc_type', models.CharField(choices=[('id_card', 'شناسنامه'), ('register_form', 'فرم ثبت نام'), ('insurance_card', 'بیمه ورزشی'), ('other', 'سایر')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='training.enrollment')),
            ],
            options={
                'verbose_name': 'مدرک ثبت نام',
                'verbose_name_plural': 'مدارک ثبت نام',
            },
        ),
    ]
