# Generated by Django 5.2.8 on 2025-12-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_agerange_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_status',
            field=models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی')], max_length=10, verbose_name='نوع کلاس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='gender',
            field=models.CharField(choices=[('male', 'آقایان'), ('female', 'بانوان'), ('both', 'عمومی')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.DeleteModel(
            name='EnrollmentDocument',
        ),
    ]
