# Generated by Django 5.2.8 on 2026-02-14 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_enrollment_unique_together_course_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='note',
            field=models.TextField(default=' ', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='training.enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('time_table', 'date')},
        ),
    ]
