# Generated by Django 5.2.8 on 2026-02-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date'], 'verbose_name': 'جلسه', 'verbose_name_plural': 'جلسات'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10, null=True),
        ),
    ]
