# Generated by Django 5.2.8 on 2026-02-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_session_options_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='attendance_status',
            field=models.CharField(choices=[('finished', 'Finished'), ('unfinished', 'Unfinished')], default='unfinished', max_length=10),
        ),
    ]
