# Generated by Django 5.2.8 on 2026-04-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_session_attendance_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('course', 'day_of_week', 'start_time', 'end_time'), name='unique_timetable_course_day_start_end'),
        ),
    ]
