# Generated by Django 5.2.8 on 2026-04-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_alter_enrollment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='custom_due_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='مثلاً 7 یعنی هفتم هر ماه', null=True),
        ),
    ]
