# Generated by Django 5.2.8 on 2026-04-29 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_enrollment_custom_due_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='custom_due_day',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='مثلاً 7 یعنی هفتم هر ماه', null=True),
        ),
    ]
