# Generated by Django 5.2.8 on 2026-05-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_enrollment_end_date_enrollment_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='days_group',
            field=models.CharField(choices=[('even', 'زوج'), ('odd', 'فرد'), ('mixed', 'ترکیبی')], default='mixed', max_length=10),
        ),
    ]
