# Generated by Django 5.2.8 on 2026-05-26 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_course_days_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'roles': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='مربی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='days_group',
            field=models.CharField(choices=[('even', 'زوج'), ('odd', 'فرد'), ('mixed', 'ترکیبی')], default='mixed', max_length=10, verbose_name='گروه روزهای کلاس'),
        ),
    ]
