# Generated by Django 5.2.8 on 2026-02-23 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='verb',
            field=models.CharField(choices=[('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('schedule_create', 'Schedule Create'), ('schedule_update', 'Schedule Update'), ('schedule_delete', 'Schedule Delete'), ('user_register', 'User Register'), ('user_login', 'User Login')], max_length=64),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['target_ct', 'target_id'], name='activity_ac_target__2bae7c_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-created_at'], name='activity_ac_created_d34040_idx'),
        ),
    ]
