# Generated by Django 5.2.8 on 2026-02-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activitylog_verb_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- 1) ساخت جدول جدید پارتیشن‌شده (بر اساس created_at)
            CREATE TABLE activity_activitylog_p (
                LIKE activity_activitylog INCLUDING DEFAULTS INCLUDING IDENTITY EXCLUDING CONSTRAINTS EXCLUDING INDEXES
            ) PARTITION BY RANGE (created_at);


            ALTER TABLE activity_activitylog_p
            ADD PRIMARY KEY (id, created_at);

            CREATE INDEX activity_activitylog_actor_created_at_idx
            ON activity_activitylog_p (actor_id, created_at DESC);

            CREATE INDEX activity_activitylog_verb_created_at_idx
            ON activity_activitylog_p (verb, created_at DESC);

            CREATE INDEX activity_activitylog_target_idx
            ON activity_activitylog_p (target_ct_id, target_id);

            CREATE INDEX activity_activitylog_created_at_idx
            ON activity_activitylog_p (created_at DESC);

            -- 2) پارتیشن پیش‌فرض (هر رکوردی که جای مشخص ندارد اینجا می‌افتد)
            CREATE TABLE activity_activitylog_default
            PARTITION OF activity_activitylog_p
            DEFAULT;

            -- 3) پارتیشن برای همین ماه (فوریه 2026)
            CREATE TABLE activity_activitylog_2026_02
            PARTITION OF activity_activitylog_p
            FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');

            -- 4) انتقال داده‌ها از جدول فعلی
            INSERT INTO activity_activitylog_p
            SELECT * FROM activity_activitylog;

            -- 5) عوض کردن اسم جدول‌ها
            ALTER TABLE activity_activitylog RENAME TO activity_activitylog_old;
            ALTER TABLE activity_activitylog_p RENAME TO activity_activitylog;

            -- 6) حذف جدول قدیمی (فعلاً کامنت می‌گذاریم)
            -- DROP TABLE activity_activitylog_old;
            """,
            reverse_sql="""
            -- بازگشت خودکار ندارد (اگر لازم شد دستی برمی‌گردانیم)
            """
        ),
    ]
