# Generated by Django 5.2.8 on 2026-02-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_partition_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='verb',
            field=models.CharField(choices=[('athlete_login', 'ورزشکار: ورود به سیستم'), ('athlete_update_profile', 'ورزشکار: بروزرسانی پروفایل'), ('athlete_change_password', 'ورزشکار: تغییر رمز عبور'), ('athlete_pay_tuition', 'ورزشکار: پرداخت شهریه'), ('coach_login', 'مربی: ورود به سیستم'), ('coach_change_password', 'مربی: تغییر رمز عبور'), ('coach_update_profile', 'مربی: بروزرسانی پروفایل'), ('coach_record_tuition', 'مربی: ثبت شهریه'), ('coach_record_attendance', 'مربی: ثبت حضور و غیاب'), ('coach_register_athlete', 'مربی: ثبت نام ورزشکار جدید'), ('coach_add_athlete_to_class', 'مربی: اضافه کردن ورزشکار جدید به کلاس'), ('manager_login', 'مدیر: ورود به سیستم'), ('manager_change_password', 'مدیر: تغییر رمز عبور'), ('manager_update_profile', 'مدیر: بروزرسانی پروفایل'), ('manager_record_tuition', 'مدیر: ثبت شهریه'), ('manager_record_attendance', 'مدیر: ثبت حضور و غیاب'), ('manager_register_athlete', 'مدیر: ثبت نام ورزشکار جدید'), ('manager_add_athlete_to_class', 'مدیر: اضافه کردن ورزشکار جدید به کلاس')], max_length=64),
        ),
    ]
