# Generated by Django 5.2.8 on 2025-12-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcementrecipient',
            options={'verbose_name': 'دریافت کننده اطلاعیه', 'verbose_name_plural': 'دریافت کننده های اطلاعیه ها'},
        ),
    ]
