# Generated by Django 5.2.8 on 2026-05-26 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_customuser_insurance_and_more'),
        ('announcements', '0002_alter_announcementrecipient_options'),
        ('training', '0014_alter_course_coach_alter_course_days_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='user',
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='عنوان')),
                ('descriptions', models.TextField(verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('p', 'Published'), ('b', 'Back'), ('d', 'Draft'), ('r', 'Review')], default='d', max_length=1, verbose_name='وضعیت')),
                ('target_type', models.CharField(choices=[('all', 'همه'), ('role', 'نقش'), ('class', 'کلاس')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('target_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.course')),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رسید خوانده شدن اطلاعیه',
                'verbose_name_plural': 'رسیدهای خوانده شدن اطلاعیه\u200cها',
                'unique_together': {('announcement', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='AnnouncementRecipient',
        ),
        migrations.DeleteModel(
            name='Announcements',
        ),
    ]
