# Generated by Django 5.2.8 on 2026-05-26 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_customuser_insurance_and_more'),
        ('announcements', '0003_remove_announcements_recipients_and_more'),
        ('training', '0014_alter_course_coach_alter_course_days_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='target_class',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='target_role',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='target_type',
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_classes',
            field=models.ManyToManyField(blank=True, to='training.course'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_roles',
            field=models.ManyToManyField(blank=True, to='account.role'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcementread',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_logs', to='announcements.announcement'),
        ),
        migrations.AlterField(
            model_name='announcementread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['created_at'], name='announcemen_created_40a59f_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['user'], name='announcemen_user_id_e7ced7_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['announcement'], name='announcemen_announc_cd358e_idx'),
        ),
    ]
