# Generated by Django 5.2.8 on 2026-02-20 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0008_session_attendance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='سال دوره')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='ماه دوره (۱-۱۲)')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ کل')),
                ('status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('partially_paid', 'نیمه پرداخت'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده')], default='unpaid', max_length=20, verbose_name='وضعیت')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='سررسید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='training.enrollment', verbose_name='ثبت\u200c نام')),
            ],
            options={
                'verbose_name': 'صورتحساب',
                'verbose_name_plural': 'صورتحساب\u200cها',
                'ordering': ['-created_at'],
                'unique_together': {('enrollment', 'period_year', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ پرداخت')),
                ('method', models.CharField(choices=[('online', 'آنلاین'), ('cash', 'نقدی'), ('pos', 'کارت\u200cخوان'), ('transfer', 'کارت به کارت/واریز')], default='online', max_length=20, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('refunded', 'مسترد شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.invoice', verbose_name='صورتحساب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت\u200cکننده')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('idpay', 'آیدی\u200cپی'), ('other', 'سایر')], default='zarinpal', max_length=50, verbose_name='درگاه')),
                ('authority', models.CharField(blank=True, max_length=100, verbose_name='Authority / Track ID')),
                ('ref_id', models.CharField(blank=True, max_length=100, verbose_name='کد پیگیری نهایی')),
                ('card_mask', models.CharField(blank=True, max_length=30, verbose_name='شماره کارت ماسک\u200cشده')),
                ('raw_request', models.JSONField(blank=True, null=True, verbose_name='درخواست به درگاه (خام)')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='پاسخ درگاه (خام)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_detail', to='payment.payment', verbose_name='پرداخت')),
            ],
            options={
                'verbose_name': 'پرداخت آنلاین',
                'verbose_name_plural': 'پرداخت\u200cهای آنلاین',
            },
        ),
    ]
