# Generated by Django 5.2.8 on 2026-02-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='base_monthly_fee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شهریه ماهانه پایه'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billed_days',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='تعداد روزهای قابل محاسبه'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='days_in_period',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='تعداد روزهای دوره'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='پایان دوره'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='شروع دوره'),
        ),
    ]
