# Generated by Django 5.2.8 on 2026-04-22 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_invoice_base_monthly_fee_invoice_billed_days_and_more'),
        ('training', '0010_alter_enrollment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='base_monthly_fee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شهریه ما0هانه پایه'),
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='training.enrollment')),
            ],
        ),
    ]
