# Generated by Django 5.2.8 on 2026-04-22 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_invoice_base_monthly_fee_pricingrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingrule',
            options={'verbose_name': 'قانون قیمت\u200cگذاری', 'verbose_name_plural': 'قوانین قیمت\u200cگذاری'},
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
