# Generated by Django 5.2.8 on 2026-04-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_pricingrule_options_pricingrule_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='manual_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ دستی (در صورت وجود)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='manual_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='سررسید دستی (در صورت وجود)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='manual_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='ثبت دلیل تغییر'),
        ),
    ]
