# Generated by Django 5.2.8 on 2026-04-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_invoice_manual_amount_invoice_manual_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='manual_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ثبت دلیل تغییر'),
        ),
    ]
