# Generated by Django 5.2.8 on 2026-04-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_invoice_manual_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='overdue_notified_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
