# Generated by Django 5.2.8 on 2026-04-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_invoice_overdue_notified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین اخطار'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='overdue_notified_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد اخطار پس از سررسید'),
        ),
    ]
